"""S19 + S20 - composes `db/seed/05_regional.sql`.

Plan 4.1 lists one seed file carrying three tables: `hotspots` (geometry only),
`environmental_events` and `satellite_tiles`. Three scripts produce those rows,
so this is the single writer of that file. One file, one writer.

    python -m prep.build_regional                      synthetic events and tiles
    python -m prep.build_regional --source=live        NASA EONET and NASA GIBS
    python -m prep.build_regional --source=frozen      replay both committed feeds
    python -m prep.build_regional --print              show what would be written

The three parts come from `prep/build_hotspots.py`, `prep/fetch_events.py` and
`prep/fetch_tiles.py`. None of them writes a file; each returns its own SQL.

ADR-7: the one spatial decision in this file
--------------------------------------------
`environmental_events.hotspot_id` is assigned at the END of the composed file by
a PostGIS statement, not by any of the three producers. Associating an event with
a hotspot is a spatial decision, and spatial decisions have exactly one owner, in
the database, for the same reason `v_hotspot_membership` owns collateral
containment.

The association is deliberately far looser than membership. An event is regional
pressure, not a property inside a boundary: peat smoke three hundred kilometres
upwind genuinely bears on a hotspot, while a collateral that far away plainly
does not sit in it. So an event attaches to the NEAREST hotspot within
`EVENT_ASSOCIATION_KM`, and to nothing at all beyond that. Most of the news list
therefore contributes nothing to any hotspot's V term, which is correct: those
rows are regional context, not pressure on a particular book.
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import List, Optional, Sequence

from prep import build_hotspots, fetch_events, fetch_tiles
from prep.lib import frozen as frozen_lib
from prep.lib.synthetic import load_portfolio

SEED_SQL = os.path.join("db", "seed", "05_regional.sql")

#: How far an event may be from a hotspot centroid and still count as pressure on
#: it. Far more generous than containment, because that is what an event is.
#:
#: Calibrated on transboundary haze, which is the real regional-pressure
#: mechanism in this basin: smoke from Sumatran and Kalimantan peat fires reaches
#: Singapore and the Klang valley routinely, over roughly 300 km. 400 km covers
#: that with a margin and stops well short of absurdity.
#:
#: Measured against the seeded feed, the choice matters and is not arbitrary:
#: at 75 km one event of 58 attaches, to a single hotspot, which would leave the
#: reference index's V term at zero for fifteen of sixteen. At 400 km, 11 events
#: attach across 7 hotspots. At 600 km, 35 attach across 10, but that is a
#: Borneo fire bearing on Shanghai, which is not a claim worth making to a board.
EVENT_ASSOCIATION_KM = 400.0

SOURCES = ("live", "frozen", "synthetic")


def header(source: str, hotspots: int, events: int, tiles: int) -> str:
    return f"""-- db/seed/05_regional.sql
--
-- GENERATED by `python -m prep.build_regional --source={source}`. Do not hand-edit;
-- rerun the generator instead.
--
-- {hotspots} hotspots, {events} environmental events, {tiles} satellite tiles.
--
-- Three producers, one writer: prep/build_hotspots.py, prep/fetch_events.py and
-- prep/fetch_tiles.py each return SQL, and prep/build_regional.py writes this file.
--
-- No BEGIN or COMMIT: scripts/seed.ts wraps every seed file in its own transaction.
"""


def association_sql() -> str:
    return f"""-- ADR-7: the ONE spatial decision in this file, and PostGIS makes it.
--
-- Neither fetch_events.py nor build_hotspots.py writes hotspot_id. An event is
-- attached to the NEAREST hotspot within {EVENT_ASSOCIATION_KM:.0f} km of its centroid, and to
-- nothing beyond that. The rule is looser than collateral containment on purpose:
-- an event is regional pressure rather than something inside a boundary, so a
-- storm offshore bears on a coastal hotspot while a property that far away
-- plainly does not sit in it.
--
-- Events outside every radius keep hotspot_id NULL. They still render on the news
-- list, and they contribute nothing to any hotspot's V term, which is the correct
-- reading rather than a missing one.
--
-- A correlated subquery rather than a lateral join: an UPDATE's target table is
-- not in scope for a LATERAL in its own FROM clause. This form also sets NULL by
-- itself when nothing matches, so a stale association from an earlier run cannot
-- survive a reseed and no second statement is needed to clear one.
UPDATE environmental_events e
SET hotspot_id = (
  SELECT h.id
  FROM hotspots h
  WHERE ST_DWithin(e.location, h.centroid, {EVENT_ASSOCIATION_KM * 1000:.0f})
  ORDER BY ST_Distance(e.location, h.centroid)
  LIMIT 1
)
WHERE e.location IS NOT NULL;
"""


def compose(source: str, write_files: bool = True) -> tuple[str, int, int, int]:
    portfolio = load_portfolio()
    samples = frozen_lib.read("synthetic", "hazard_samples", required=False)

    hotspots = build_hotspots.build(portfolio, samples)
    events = fetch_events.collect(source)
    tiles = fetch_tiles.collect(source, write_files=write_files)

    parts = [
        header(source, len(hotspots), len(events), len(tiles)),
        build_hotspots.hotspots_sql(hotspots),
        fetch_events.events_sql(events),
        fetch_tiles.tiles_sql(tiles),
        association_sql(),
    ]

    return "\n".join(parts), len(hotspots), len(events), len(tiles)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m prep.build_regional",
        description="Compose db/seed/05_regional.sql from hotspots, events and tiles.",
    )
    parser.add_argument("--source", choices=SOURCES, default="synthetic",
                        help="which feed the events and tiles come from")
    parser.add_argument("--print", action="store_true", dest="print_only",
                        help="report what would be written and write nothing")
    args = parser.parse_args(argv)

    try:
        sql, hotspots, events, tiles = compose(args.source, write_files=not args.print_only)
    except (fetch_events.FeedUnavailable, fetch_tiles.TilesUnavailable,
            frozen_lib.FrozenUnavailable) as exc:
        print(f"\n[regional] {exc}", file=sys.stderr)
        print("[regional] Nothing was written. --source=synthetic needs nothing external.",
              file=sys.stderr)
        return 1

    print(f"[regional] source={args.source}: {hotspots} hotspots, {events} events, {tiles} tiles")

    if args.print_only:
        print(f"[regional] --print: {len(sql):,} bytes would be written to {SEED_SQL}")
        return 0

    full = os.path.join(frozen_lib.repo_root(), SEED_SQL)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(sql)

    print(f"[regional] wrote {full}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
