/**
 * The illustrative-data ribbon (S27; plan 4.9, a spec non-goal made explicit).
 *
 * Every S$ figure in this application is derived from a synthetic portfolio
 * generated by `prep/gen_portfolio.py` and a synthetic hazard floor from
 * `prep/lib/synthetic.py`. None of it describes a real borrower, a real
 * property or a real loan, and no screen may be read as a credit decision.
 *
 * It appears on EVERY screen, the sign-in page included, which is the point:
 * a screenshot of any single screen has to carry the disclaimer with it, and a
 * disclaimer that only exists behind a login is not on the screenshot that
 * leaves the room.
 *
 * It is not a banner to be dismissed and it has no close control. On paper it
 * prints once, at the top of the sheet, as plain text rather than a coloured
 * bar; the `@media print` block in `app/globals.css` flattens the colours.
 */

export const ILLUSTRATIVE_TEXT =
  'Synthetic portfolio, illustrative figures. Not a credit decision.';

export function IllustrativeRibbon({ className = '' }: { className?: string }) {
  return (
    <div
      role="note"
      data-testid="illustrative-ribbon"
      className={
        'border-b border-caution-rule bg-caution-bg px-4 py-1 text-center text-[11px] ' +
        'font-medium tracking-wide text-caution-fg ' +
        className
      }
    >
      {ILLUSTRATIVE_TEXT}
    </div>
  );
}

export default IllustrativeRibbon;
