-- db/seed/05_regional.sql
--
-- GENERATED by `python -m prep.build_regional --source=frozen`. Do not hand-edit;
-- rerun the generator instead.
--
-- 16 hotspots, 58 environmental events, 12 satellite tiles,
-- and the per-property thumbnail paths.
--
-- Four producers, one writer: prep/build_hotspots.py, prep/fetch_events.py,
-- prep/fetch_tiles.py and prep/fetch_thumbs.py each return SQL, and
-- prep/build_regional.py writes this file.
--
-- No BEGIN or COMMIT: scripts/seed.ts wraps every seed file in its own transaction.

-- 16 hotspots, POLYGONS AND RADII ONLY (ADR-7). This section writes no
-- membership and no exposure. `v_hotspot_membership` is the single definition of
-- which collateral belongs to which hotspot, and `v_hotspot_exposure` computes
-- the S$ on top of it, so `hotspots` carries neither a loan_exposure_sgd nor an
-- exposure_share column and nothing here tries to supply one.
--
-- Exactly one shape each: the CHECK constraint rejects a hotspot carrying both a
-- polygon and a radius, which is what makes the membership UNION incapable of
-- emitting a duplicate pair.
INSERT INTO hotspots (id, name, country, centroid, area, radius_m, hazard_type, summary) VALUES
  ('HS-CN-PRD', 'Pearl River Delta', 'CN', ST_SetSRID(ST_MakePoint(113.704631, 22.656628), 4326)::geography, ST_SetSRID(ST_MakePolygon(ST_GeomFromText('LINESTRING(113.517957 22.522055, 113.902957 22.522055, 113.902957 22.787540, 113.517957 22.787540, 113.517957 22.522055)')), 4326)::geography, NULL, 'heat', 'Nansha and Qianhai, two reclaimed delta developments carrying both typhoon wind and chronic air quality.'),
  ('HS-CN-SHANGHAI', 'Pudong and Lujiazui', 'CN', ST_SetSRID(ST_MakePoint(121.510147, 31.229883), 4326)::geography, NULL, 2766.5, 'heat', 'The Huangpu financial district on the Yangtze delta, behind the Shanghai 200-year seawall standard.'),
  ('HS-CN-XIAMEN', 'Xiamen', 'CN', ST_SetSRID(ST_MakePoint(118.093173, 24.485175), 4326)::geography, NULL, 2100.6, 'heat', 'Island city on the Taiwan Strait, one of the most typhoon-exposed points in the portfolio.'),
  ('HS-HK-HARBOUR', 'Victoria Harbour east', 'HK', ST_SetSRID(ST_MakePoint(114.235917, 22.309522), 4326)::geography, ST_SetSRID(ST_MakePolygon(ST_GeomFromText('LINESTRING(114.195002 22.271269, 114.273174 22.271269, 114.273174 22.341259, 114.195002 22.341259, 114.195002 22.271269)')), 4326)::geography, NULL, 'heat', 'Tseung Kwan O, Heng Fa Chuen and Kai Tak: three reclaimed harbourfront developments with high-rise reinforced-concrete stock.'),
  ('HS-HK-NT', 'New Territories and Lantau', 'HK', ST_SetSRID(ST_MakePoint(114.072312, 22.378231), 4326)::geography, ST_SetSRID(ST_MakePolygon(ST_GeomFromText('LINESTRING(113.942390 22.280808, 114.187812 22.280808, 114.187812 22.468562, 113.942390 22.468562, 113.942390 22.280808)')), 4326)::geography, NULL, 'heat', 'Tai Po, Sha Tin and Tung Chung. Hillside development where the landslide manual-review flag concentrates.'),
  ('HS-ID-JAKARTA', 'Central Jakarta and BSD', 'ID', ST_SetSRID(ST_MakePoint(106.731679, -6.245426), 4326)::geography, ST_SetSRID(ST_MakePolygon(ST_GeomFromText('LINESTRING(106.640102 -6.313461, 106.845955 -6.313461, 106.845955 -6.168995, 106.640102 -6.168995, 106.640102 -6.313461)')), 4326)::geography, NULL, 'heat', 'The inland half of the Jakarta exposure, from the central business district out to the BSD City satellite development.'),
  ('HS-ID-NJAKARTA', 'North Jakarta', 'ID', ST_SetSRID(ST_MakePoint(106.786649, -6.117679), 4326)::geography, NULL, 2232.8, 'flood_coastal', 'Pluit, Muara Baru and Ancol. The most subsident ground in the portfolio, behind the NCICD coastal wall, much of it already below sea level.'),
  ('HS-ID-SEMARANG', 'Semarang north coast', 'ID', ST_SetSRID(ST_MakePoint(110.420933, -6.948098), 4326)::geography, NULL, 2545.6, 'flood_coastal', 'Subsiding north-coast Java, protected by the Banger polder scheme.'),
  ('HS-ID-SURABAYA', 'Surabaya', 'ID', ST_SetSRID(ST_MakePoint(112.737320, -7.226501), 4326)::geography, NULL, 2668.5, 'flood_riverine', 'East Java port city on the Madura Strait.'),
  ('HS-MY-JOHOR', 'Danga Bay, Johor Bahru', 'MY', ST_SetSRID(ST_MakePoint(103.705574, 1.469480), 4326)::geography, NULL, 2686.3, 'flood_coastal', 'Reclaimed waterfront development on the Johor Strait facing Singapore.'),
  ('HS-MY-KLANG', 'Klang Valley', 'MY', ST_SetSRID(ST_MakePoint(101.607738, 3.107863), 4326)::geography, ST_SetSRID(ST_MakePolygon(ST_GeomFromText('LINESTRING(101.485284 3.044725, 101.729882 3.044725, 101.729882 3.166948, 101.485284 3.166948, 101.485284 3.044725)')), 4326)::geography, NULL, 'heat', 'The Kuala Lumpur conurbation from the city centre down the Klang valley to Kuala Langat, drained by the SMART tunnel catchment.'),
  ('HS-SG-CENTRAL', 'Bukit Timah', 'SG', ST_SetSRID(ST_MakePoint(103.772315, 1.340357), 4326)::geography, NULL, 1309.9, 'heat', 'Elevated central catchment. The highest ground in the portfolio and the least coastal exposure in Singapore.'),
  ('HS-SG-EASTCOAST', 'East Coast and Katong', 'SG', ST_SetSRID(ST_MakePoint(103.906565, 1.301844), 4326)::geography, NULL, 1605.5, 'flood_riverine', 'A dense residential strip on reclaimed land between the East Coast Parkway and the sea, inside the Long Island protection study area.'),
  ('HS-SG-MARINA', 'Marina Bay and Kallang Basin', 'SG', ST_SetSRID(ST_MakePoint(103.865688, 1.287217), 4326)::geography, NULL, 3433.9, 'flood_coastal', 'Reclaimed waterfront and the Kallang river mouth. Low ground behind the Marina Barrage, where the coastal and riverine perils overlap.'),
  ('HS-SG-NORTH', 'Woodlands', 'SG', ST_SetSRID(ST_MakePoint(103.792256, 1.434566), 4326)::geography, NULL, 1268.3, 'heat', 'Inland northern residential district on the Johor Strait.'),
  ('HS-SG-SOUTHWEST', 'Sentosa Cove and Jurong Island', 'SG', ST_SetSRID(ST_MakePoint(103.777595, 1.253091), 4326)::geography, ST_SetSRID(ST_MakePolygon(ST_GeomFromText('LINESTRING(103.684176 1.235772, 103.846871 1.235772, 103.846871 1.281640, 103.684176 1.281640, 103.684176 1.235772)')), 4326)::geography, NULL, 'flood_coastal', 'Two very different waterfronts on one exposure: high-value resort housing and a petrochemical estate, both on reclaimed coastal land.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, country = EXCLUDED.country, centroid = EXCLUDED.centroid,
  area = EXCLUDED.area, radius_m = EXCLUDED.radius_m,
  hazard_type = EXCLUDED.hazard_type, summary = EXCLUDED.summary;

-- Any hotspot this run no longer claims is removed, so a regenerated file is
-- authoritative rather than merely additive. environmental_events.hotspot_id is
-- ON DELETE SET NULL, so an event outlives a retired hotspot.
DELETE FROM hotspots WHERE id NOT IN ('HS-CN-PRD', 'HS-CN-SHANGHAI', 'HS-CN-XIAMEN', 'HS-HK-HARBOUR', 'HS-HK-NT', 'HS-ID-JAKARTA', 'HS-ID-NJAKARTA', 'HS-ID-SEMARANG', 'HS-ID-SURABAYA', 'HS-MY-JOHOR', 'HS-MY-KLANG', 'HS-SG-CENTRAL', 'HS-SG-EASTCOAST', 'HS-SG-MARINA', 'HS-SG-NORTH', 'HS-SG-SOUTHWEST');

-- The count AC-15 and plan S19 rest on.
DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM hotspots;
  IF n <> 16 THEN
    RAISE EXCEPTION '05_regional.sql expected 16 hotspots, found %', n;
  END IF;
END $$;

-- 58 environmental events, newest first. AC-16 asks for at least 10 with a
-- source and a date; this seeds 58. 58 fall inside the 90-day window the
-- reference index's V term counts; the rest are shown on the news list and weigh nothing,
-- which is a correct reading rather than a missing one.
--
-- hotspot_id is deliberately absent here. Associating an event with a hotspot is a
-- spatial decision and PostGIS owns it, in the statement at the end of this file.
INSERT INTO environmental_events (id, title, event_type, occurred_on, location, source_feed, source_url, dedupe_key) VALUES
  ('EONET_24010', 'Wildfire in Indonesia 1031724', 'fire', '2026-09-03'::date, ST_SetSRID(ST_MakePoint(111.05683, -3.00360), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031724', 'eonet:EONET_24010'),
  ('EONET_22926', 'Typhoon Saudel', 'storm', '2026-09-03'::date, ST_SetSRID(ST_MakePoint(117.40000, 23.80000), 4326)::geography, 'NASA EONET', 'https://www.metoc.navy.mil/jtwc/products/wp1726.tcw', 'eonet:EONET_22926'),
  ('EONET_24020', 'Wildfire in Indonesia 1031701', 'fire', '2026-08-31'::date, ST_SetSRID(ST_MakePoint(105.27133, -2.93094), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031701', 'eonet:EONET_24020'),
  ('EONET_23974', 'Wildfire in Indonesia 1031674', 'fire', '2026-08-28'::date, ST_SetSRID(ST_MakePoint(113.77609, -3.22177), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031674', 'eonet:EONET_23974'),
  ('EONET_23764', 'Wildfire in Indonesia 1031458', 'fire', '2026-08-27'::date, ST_SetSRID(ST_MakePoint(117.94516, 2.42541), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031458', 'eonet:EONET_23764'),
  ('EV-CURATED-BSD-POLLUTION', 'Cisadane river pollution incident near BSD City, Tangerang', 'pollution', '2026-08-27'::date, ST_SetSRID(ST_MakePoint(106.65120, -6.30090), 4326)::geography, 'curated', 'https://www.gdacs.org/', 'EV-CURATED-BSD-POLLUTION'),
  ('EONET_24043', 'Wildfire in Indonesia 1031689', 'fire', '2026-08-26'::date, ST_SetSRID(ST_MakePoint(109.60315, -0.15934), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031689', 'eonet:EONET_24043'),
  ('EONET_23634', 'Wildfire in Indonesia 1031350', 'fire', '2026-08-25'::date, ST_SetSRID(ST_MakePoint(110.03149, -1.13747), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031350', 'eonet:EONET_23634'),
  ('EONET_23833', 'Wildfire in Indonesia 1031521', 'fire', '2026-08-25'::date, ST_SetSRID(ST_MakePoint(112.90724, -8.04654), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031521', 'eonet:EONET_23833'),
  ('EONET_23909', 'Wildfire in Indonesia 1031554', 'fire', '2026-08-25'::date, ST_SetSRID(ST_MakePoint(111.08972, -2.73910), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031554', 'eonet:EONET_23909'),
  ('EONET_23207', 'Tropical Storm Narra', 'storm', '2026-08-25'::date, ST_SetSRID(ST_MakePoint(109.60000, 20.00000), 4326)::geography, 'NASA EONET', 'https://www.metoc.navy.mil/jtwc/products/wp1826.tcw', 'eonet:EONET_23207'),
  ('EONET_23541', 'Wildfire in Indonesia 1031304', 'fire', '2026-08-24'::date, ST_SetSRID(ST_MakePoint(111.22659, -2.90126), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031304', 'eonet:EONET_23541'),
  ('EONET_23594', 'Wildfire in Indonesia 1031320', 'fire', '2026-08-24'::date, ST_SetSRID(ST_MakePoint(114.68380, -2.72464), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031320', 'eonet:EONET_23594'),
  ('EONET_24046', 'Wildfire in Indonesia 1031720', 'fire', '2026-08-23'::date, ST_SetSRID(ST_MakePoint(114.05635, -3.10306), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031720', 'eonet:EONET_24046'),
  ('EONET_24047', 'Wildfire in Indonesia 1031727', 'fire', '2026-08-23'::date, ST_SetSRID(ST_MakePoint(109.05481, 0.45960), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031727', 'eonet:EONET_24047'),
  ('EONET_23725', 'Wildfire in Indonesia 1031427', 'fire', '2026-08-22'::date, ST_SetSRID(ST_MakePoint(104.30667, -1.74175), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031427', 'eonet:EONET_23725'),
  ('EONET_23793', 'Wildfire in Indonesia 1031471', 'fire', '2026-08-22'::date, ST_SetSRID(ST_MakePoint(116.05965, -0.40939), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031471', 'eonet:EONET_23793'),
  ('EONET_23794', 'Wildfire in Indonesia 1031476', 'fire', '2026-08-22'::date, ST_SetSRID(ST_MakePoint(109.66450, 0.01794), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031476', 'eonet:EONET_23794'),
  ('EONET_23918', 'Wildfire in Indonesia 1031593', 'fire', '2026-08-22'::date, ST_SetSRID(ST_MakePoint(104.32912, -2.44697), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031593', 'eonet:EONET_23918'),
  ('EONET_23919', 'Wildfire in Indonesia 1031594', 'fire', '2026-08-22'::date, ST_SetSRID(ST_MakePoint(109.64295, -0.90545), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031594', 'eonet:EONET_23919'),
  ('EONET_24048', 'Wildfire in Indonesia 1031690', 'fire', '2026-08-22'::date, ST_SetSRID(ST_MakePoint(114.50498, -3.05300), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031690', 'eonet:EONET_24048'),
  ('EONET_24049', 'Wildfire in Indonesia 1031729', 'fire', '2026-08-22'::date, ST_SetSRID(ST_MakePoint(105.29917, -3.11550), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031729', 'eonet:EONET_24049'),
  ('EONET_24050', 'Wildfire in Indonesia 1031721', 'fire', '2026-08-21'::date, ST_SetSRID(ST_MakePoint(103.47870, -2.27850), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031721', 'eonet:EONET_24050'),
  ('EONET_23650', 'Wildfire in Indonesia 1031374', 'fire', '2026-08-20'::date, ST_SetSRID(ST_MakePoint(114.94929, -2.71049), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031374', 'eonet:EONET_23650'),
  ('EONET_24004', 'Wildfire in Indonesia 1031664', 'fire', '2026-08-20'::date, ST_SetSRID(ST_MakePoint(109.52282, -0.81118), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031664', 'eonet:EONET_24004'),
  ('EONET_23359', 'Wildfire in Indonesia 1031147', 'fire', '2026-08-19'::date, ST_SetSRID(ST_MakePoint(105.71195, -3.59419), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031147', 'eonet:EONET_23359'),
  ('EONET_23604', 'Wildfire in Indonesia 1031348', 'fire', '2026-08-18'::date, ST_SetSRID(ST_MakePoint(109.89745, -1.03830), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031348', 'eonet:EONET_23604'),
  ('EV-CURATED-BORNEO-FIRE', 'Peatland forest fire, Central Kalimantan, Borneo', 'fire', '2026-08-18'::date, ST_SetSRID(ST_MakePoint(113.92140, -2.20880), 4326)::geography, 'curated', 'https://firms.modaps.eosdis.nasa.gov/', 'EV-CURATED-BORNEO-FIRE'),
  ('EONET_23315', 'Wildfire in Indonesia 1031106', 'fire', '2026-08-17'::date, ST_SetSRID(ST_MakePoint(112.05437, -0.29972), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031106', 'eonet:EONET_23315'),
  ('EONET_23799', 'Wildfire in Indonesia 1031474', 'fire', '2026-08-17'::date, ST_SetSRID(ST_MakePoint(110.10021, -0.61214), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031474', 'eonet:EONET_23799'),
  ('EONET_23578', 'Wildfire in Indonesia 1031308', 'fire', '2026-08-14'::date, ST_SetSRID(ST_MakePoint(112.92257, -2.57712), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031308', 'eonet:EONET_23578'),
  ('EONET_22969', 'Wildfire in Indonesia 1030809', 'fire', '2026-08-13'::date, ST_SetSRID(ST_MakePoint(115.10384, -2.85016), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030809', 'eonet:EONET_22969'),
  ('EONET_23112', 'Wildfire in Indonesia 1030876', 'fire', '2026-08-13'::date, ST_SetSRID(ST_MakePoint(110.40624, -1.99902), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030876', 'eonet:EONET_23112'),
  ('EONET_23279', 'Wildfire in Indonesia 1031052', 'fire', '2026-08-13'::date, ST_SetSRID(ST_MakePoint(110.95414, -3.00728), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031052', 'eonet:EONET_23279'),
  ('EONET_23526', 'Wildfire in Indonesia 1031254', 'fire', '2026-08-13'::date, ST_SetSRID(ST_MakePoint(112.85554, -2.68432), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031254', 'eonet:EONET_23526'),
  ('EONET_23527', 'Wildfire in Indonesia 1031217', 'fire', '2026-08-13'::date, ST_SetSRID(ST_MakePoint(110.18817, -1.82402), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1031217', 'eonet:EONET_23527'),
  ('EONET_23114', 'Wildfire in Indonesia 1030913', 'fire', '2026-08-12'::date, ST_SetSRID(ST_MakePoint(114.00077, -3.20227), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030913', 'eonet:EONET_23114'),
  ('EONET_23118', 'Wildfire in Indonesia 1030879', 'fire', '2026-08-09'::date, ST_SetSRID(ST_MakePoint(110.48535, -2.21399), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030879', 'eonet:EONET_23118'),
  ('EONET_23119', 'Wildfire in Indonesia, Timor-Leste 1030914', 'fire', '2026-08-09'::date, ST_SetSRID(ST_MakePoint(124.10949, -9.44674), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030914', 'eonet:EONET_23119'),
  ('EONET_21776', 'Super Typhoon Dolphin', 'storm', '2026-08-09'::date, ST_SetSRID(ST_MakePoint(120.60000, 27.90000), 4326)::geography, 'NASA EONET', 'https://www.metoc.navy.mil/jtwc/products/wp1226.tcw', 'eonet:EONET_21776'),
  ('EONET_23009', 'Wildfire in Indonesia 1030791', 'fire', '2026-08-07'::date, ST_SetSRID(ST_MakePoint(110.32664, -2.30958), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030791', 'eonet:EONET_23009'),
  ('EONET_22844', 'Wildfire in Indonesia 1030660', 'fire', '2026-08-06'::date, ST_SetSRID(ST_MakePoint(110.53920, -1.99814), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030660', 'eonet:EONET_22844'),
  ('EONET_22399', 'Wildfire in Indonesia 1030312', 'fire', '2026-08-05'::date, ST_SetSRID(ST_MakePoint(109.72018, 0.71384), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030312', 'eonet:EONET_22399'),
  ('EV-CURATED-NTT-EARTHQUAKE', 'Earthquake off Flores, East Nusa Tenggara', 'earthquake', '2026-08-05'::date, ST_SetSRID(ST_MakePoint(122.97650, -8.52110), 4326)::geography, 'curated', 'https://earthquake.usgs.gov/earthquakes/map/', 'EV-CURATED-NTT-EARTHQUAKE'),
  ('EONET_22601', 'Wildfire in Indonesia 1030460', 'fire', '2026-08-02'::date, ST_SetSRID(ST_MakePoint(112.88635, -2.98180), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030460', 'eonet:EONET_22601'),
  ('EONET_22417', 'Wildfire in Indonesia 1030313', 'fire', '2026-08-01'::date, ST_SetSRID(ST_MakePoint(110.45077, 0.07468), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030313', 'eonet:EONET_22417'),
  ('EONET_22734', 'Wildfire in Indonesia 1030532', 'fire', '2026-08-01'::date, ST_SetSRID(ST_MakePoint(110.20362, -2.00800), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030532', 'eonet:EONET_22734'),
  ('EONET_22554', 'Wildfire in Indonesia 1030418', 'fire', '2026-07-31'::date, ST_SetSRID(ST_MakePoint(110.57658, 0.53245), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030418', 'eonet:EONET_22554'),
  ('EONET_22421', 'Wildfire in Indonesia 1030303', 'fire', '2026-07-30'::date, ST_SetSRID(ST_MakePoint(109.71230, -1.09956), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=WF&eventid=1030303', 'eonet:EONET_22421'),
  ('EONET_21600', 'Typhoon Noul', 'storm', '2026-07-25'::date, ST_SetSRID(ST_MakePoint(115.10000, 22.40000), 4326)::geography, 'NASA EONET', 'https://www.metoc.navy.mil/jtwc/products/wp1126.tcw', 'eonet:EONET_21600'),
  ('EONET_20877', 'Super Typhoon Bavi', 'storm', '2026-07-11'::date, ST_SetSRID(ST_MakePoint(120.40000, 28.70000), 4326)::geography, 'NASA EONET', 'https://www.metoc.navy.mil/jtwc/products/wp0926.tcw', 'eonet:EONET_20877'),
  ('EONET_20980', 'Tropical Storm Maysak', 'storm', '2026-07-04'::date, ST_SetSRID(ST_MakePoint(107.90000, 21.60000), 4326)::geography, 'NASA EONET', 'https://www.metoc.navy.mil/jtwc/products/wp1026.tcw', 'eonet:EONET_20980'),
  ('EONET_20880', 'Flood in Thailand 1103996', 'flood', '2026-06-30'::date, ST_SetSRID(ST_MakePoint(98.91858, 8.06173), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=FL&eventid=1103996', 'eonet:EONET_20880'),
  ('EONET_20882', 'Flood in Vietnam 1103992', 'flood', '2026-06-24'::date, ST_SetSRID(ST_MakePoint(106.10609, 22.74269), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=FL&eventid=1103992', 'eonet:EONET_20882'),
  ('EONET_20736', 'Flood in Myanmar 1103975', 'flood', '2026-06-23'::date, ST_SetSRID(ST_MakePoint(96.02635, 19.91049), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=FL&eventid=1103975', 'eonet:EONET_20736'),
  ('EONET_20585', 'Flood in Indonesia 1103950', 'flood', '2026-06-14'::date, ST_SetSRID(ST_MakePoint(95.97150, 4.41888), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=FL&eventid=1103950', 'eonet:EONET_20585'),
  ('EONET_20499', 'Flood in Philippines 1103942', 'flood', '2026-06-12'::date, ST_SetSRID(ST_MakePoint(124.85007, 5.88836), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=FL&eventid=1103942', 'eonet:EONET_20499'),
  ('EONET_20465', 'Flood in Malaysia 1103939', 'flood', '2026-06-10'::date, ST_SetSRID(ST_MakePoint(113.04728, 3.18743), 4326)::geography, 'NASA EONET', 'https://www.gdacs.org/report.aspx?eventtype=FL&eventid=1103939', 'eonet:EONET_20465')
ON CONFLICT (dedupe_key) DO UPDATE SET
  title = EXCLUDED.title, event_type = EXCLUDED.event_type,
  occurred_on = EXCLUDED.occurred_on, location = EXCLUDED.location,
  source_feed = EXCLUDED.source_feed, source_url = EXCLUDED.source_url;

-- 12 satellite tiles, one per metro. The strip ALWAYS renders from
-- cached_path, which points at a committed file under public/cache/tiles/, so it renders
-- with the interface disabled (AC-11, AC-14). Refresh writes a NEW file with a hash suffix
-- and updates fetched_at; a failed refresh returns a toast and changes nothing.
INSERT INTO satellite_tiles (id, region, bbox, capture_date, cached_path, live_url, fetched_at, provider) VALUES
  ('TILE-SINGAPORE', 'Singapore', '101.2500,0.0000,106.8750,5.6160', '2026-09-07'::date, '/cache/tiles/singapore-2026-09-07-2ec8fdd969.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/31/50.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-KLANG-VALLEY', 'Klang Valley', '101.2500,0.0000,106.8750,5.6160', '2026-09-07'::date, '/cache/tiles/klang-valley-2026-09-07-2ec8fdd969.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/31/50.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-PENANG', 'Penang', '95.6250,0.0000,101.2500,5.6160', '2026-09-07'::date, '/cache/tiles/penang-2026-09-07-40b512cea6.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/31/49.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-JOHOR-BAHRU', 'Johor Bahru', '101.2500,0.0000,106.8750,5.6160', '2026-09-07'::date, '/cache/tiles/johor-bahru-2026-09-07-2ec8fdd969.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/31/50.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-KOTA-KINABALU', 'Kota Kinabalu', '112.5000,5.6160,118.1250,11.1784', '2026-09-07'::date, '/cache/tiles/kota-kinabalu-2026-09-07-be245d6418.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/30/52.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-JAKARTA', 'Jakarta and BSD', '101.2500,-11.1784,106.8750,-5.6160', '2026-09-07'::date, '/cache/tiles/jakarta-2026-09-07-064fa49cf3.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/33/50.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-SEMARANG', 'Semarang', '106.8750,-11.1784,112.5000,-5.6160', '2026-09-07'::date, '/cache/tiles/semarang-2026-09-07-10f9baed2d.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/33/51.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-SURABAYA', 'Surabaya', '112.5000,-11.1784,118.1250,-5.6160', '2026-09-07'::date, '/cache/tiles/surabaya-2026-09-07-d576bd7def.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/33/52.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-SHANGHAI', 'Shanghai and Ningbo', '118.1250,27.0591,123.7500,31.9522', '2026-09-07'::date, '/cache/tiles/shanghai-2026-09-07-23a579adbb.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/26/53.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-PEARL-RIVER-DELTA', 'Guangzhou and Shenzhen', '112.5000,21.9430,118.1250,27.0591', '2026-09-07'::date, '/cache/tiles/pearl-river-delta-2026-09-07-56cb9f4747.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/27/52.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-XIAMEN', 'Xiamen', '112.5000,21.9430,118.1250,27.0591', '2026-09-07'::date, '/cache/tiles/xiamen-2026-09-07-56cb9f4747.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/27/52.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS'),
  ('TILE-HONG-KONG', 'Hong Kong', '112.5000,21.9430,118.1250,27.0591', '2026-09-07'::date, '/cache/tiles/hong-kong-2026-09-07-56cb9f4747.jpg', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-07/GoogleMapsCompatible_Level9/6/27/52.jpg', '2026-09-08T05:09:48+00:00'::timestamptz, 'NASA GIBS')
ON CONFLICT (id) DO UPDATE SET
  region = EXCLUDED.region, bbox = EXCLUDED.bbox, capture_date = EXCLUDED.capture_date,
  cached_path = EXCLUDED.cached_path, live_url = EXCLUDED.live_url,
  fetched_at = EXCLUDED.fetched_at, provider = EXCLUDED.provider;

-- ADR-7: the ONE spatial decision in this file, and PostGIS makes it.
--
-- Neither fetch_events.py nor build_hotspots.py writes hotspot_id. An event is
-- attached to the NEAREST hotspot within 400 km of its centroid, and to
-- nothing beyond that. The rule is looser than collateral containment on purpose:
-- an event is regional pressure rather than something inside a boundary, so a
-- storm offshore bears on a coastal hotspot while a property that far away
-- plainly does not sit in it.
--
-- Events outside every radius keep hotspot_id NULL. They still render on the news
-- list, and they contribute nothing to any hotspot's V term, which is the correct
-- reading rather than a missing one.
--
-- A correlated subquery rather than a lateral join: an UPDATE's target table is
-- not in scope for a LATERAL in its own FROM clause. This form also sets NULL by
-- itself when nothing matches, so a stale association from an earlier run cannot
-- survive a reseed and no second statement is needed to clear one.
UPDATE environmental_events e
SET hotspot_id = (
  SELECT h.id
  FROM hotspots h
  WHERE ST_DWithin(e.location, h.centroid, 400000)
  ORDER BY ST_Distance(e.location, h.centroid)
  LIMIT 1
)
WHERE e.location IS NOT NULL;

-- Per-property satellite thumbnail SOURCES (S43).
-- GENERATED by prep/fetch_thumbs.py through prep/build_regional.py.
--
-- `satellite_thumb_path` is written by 03_portfolio.sql from the same
-- manifest (data/frozen/satellite_thumbs.csv), so the path has exactly
-- one writer. This block writes only the source URL, which is what
-- /api/refresh/thumbs re-fetches rather than composing a URL of its own.
--
-- The case screen renders the PATH and never this URL, so the thumbnail
-- survives a disabled interface.
UPDATE collateral AS c
SET satellite_thumb_url = t.url
FROM (VALUES
  ('SG-MS-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-009', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-MS-010', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-EC-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-009', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-010', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-011', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-EC-012', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3230.jpg'),
  ('SG-SC-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-SC-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-SC-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-SC-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-SC-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-SC-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-SC-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-SC-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-JI-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3227.jpg'),
  ('SG-JI-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3227.jpg'),
  ('SG-JI-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3227.jpg'),
  ('SG-JI-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3227.jpg'),
  ('SG-JI-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3227.jpg'),
  ('SG-JI-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3227.jpg'),
  ('SG-KB-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-KB-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-KB-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-KB-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-KB-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-KB-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-KB-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-KB-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2033/3229.jpg'),
  ('SG-WL-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3228.jpg'),
  ('SG-WL-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3228.jpg'),
  ('SG-WL-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3228.jpg'),
  ('SG-WL-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3228.jpg'),
  ('SG-WL-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3228.jpg'),
  ('SG-WL-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3228.jpg'),
  ('SG-BT-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-009', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('SG-BT-010', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2032/3228.jpg'),
  ('MY-SA-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2013/3203.jpg'),
  ('MY-SA-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3203.jpg'),
  ('MY-SA-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2013/3203.jpg'),
  ('MY-SA-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2013/3203.jpg'),
  ('MY-SA-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2013/3203.jpg'),
  ('MY-SA-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2013/3202.jpg'),
  ('MY-SA-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2013/3203.jpg'),
  ('MY-SA-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2013/3203.jpg'),
  ('MY-SA-009', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3203.jpg'),
  ('MY-SA-010', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3203.jpg'),
  ('MY-KL-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3205.jpg'),
  ('MY-KL-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3205.jpg'),
  ('MY-KL-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3205.jpg'),
  ('MY-KL-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2011/3205.jpg'),
  ('MY-KL-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3205.jpg'),
  ('MY-KL-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3205.jpg'),
  ('MY-KL-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3205.jpg'),
  ('MY-KL-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2012/3205.jpg'),
  ('MY-GT-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-02/GoogleMapsCompatible_Level12/12/1986/3189.jpg'),
  ('MY-GT-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-02/GoogleMapsCompatible_Level12/12/1986/3189.jpg'),
  ('MY-GT-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-02/GoogleMapsCompatible_Level12/12/1986/3189.jpg'),
  ('MY-GT-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-02/GoogleMapsCompatible_Level12/12/1986/3189.jpg'),
  ('MY-GT-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-02/GoogleMapsCompatible_Level12/12/1986/3189.jpg'),
  ('MY-GT-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-02/GoogleMapsCompatible_Level12/12/1986/3189.jpg'),
  ('MY-GT-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-02/GoogleMapsCompatible_Level12/12/1986/3189.jpg'),
  ('MY-DB-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3227.jpg'),
  ('MY-DB-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3227.jpg'),
  ('MY-DB-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3227.jpg'),
  ('MY-DB-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3228.jpg'),
  ('MY-DB-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3227.jpg'),
  ('MY-DB-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3227.jpg'),
  ('MY-DB-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3227.jpg'),
  ('MY-DB-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2031/3227.jpg'),
  ('MY-KK-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1979/3368.jpg'),
  ('MY-KK-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1979/3368.jpg'),
  ('MY-KK-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1980/3368.jpg'),
  ('MY-KK-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1980/3368.jpg'),
  ('MY-KK-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1979/3368.jpg'),
  ('MY-KK-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1979/3368.jpg'),
  ('MY-KK-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1979/3368.jpg'),
  ('ID-PL-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3262.jpg'),
  ('ID-PL-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3262.jpg'),
  ('ID-PL-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3263.jpg'),
  ('ID-PL-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3262.jpg'),
  ('ID-PL-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3263.jpg'),
  ('ID-PL-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3263.jpg'),
  ('ID-PL-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3262.jpg'),
  ('ID-PL-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3262.jpg'),
  ('ID-PL-009', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3262.jpg'),
  ('ID-PL-010', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3263.jpg'),
  ('ID-PL-011', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3262.jpg'),
  ('ID-PL-012', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2117/3262.jpg'),
  ('ID-CJ-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2118/3263.jpg'),
  ('ID-CJ-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2118/3263.jpg'),
  ('ID-CJ-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2118/3263.jpg'),
  ('ID-CJ-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2118/3263.jpg'),
  ('ID-CJ-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2118/3263.jpg'),
  ('ID-CJ-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2118/3263.jpg'),
  ('ID-BS-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2119/3261.jpg'),
  ('ID-BS-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2119/3261.jpg'),
  ('ID-BS-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2119/3261.jpg'),
  ('ID-BS-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2119/3261.jpg'),
  ('ID-BS-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2119/3261.jpg'),
  ('ID-BS-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2119/3261.jpg'),
  ('ID-BS-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2119/3261.jpg'),
  ('ID-BS-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/2119/3261.jpg'),
  ('ID-SM-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2127/3304.jpg'),
  ('ID-SM-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2127/3304.jpg'),
  ('ID-SM-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2127/3304.jpg'),
  ('ID-SM-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2127/3304.jpg'),
  ('ID-SM-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2127/3304.jpg'),
  ('ID-SM-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2127/3304.jpg'),
  ('ID-SM-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-04/GoogleMapsCompatible_Level12/12/2127/3304.jpg'),
  ('ID-SB-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2130/3330.jpg'),
  ('ID-SB-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2130/3330.jpg'),
  ('ID-SB-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2130/3330.jpg'),
  ('ID-SB-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2130/3330.jpg'),
  ('ID-SB-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2130/3330.jpg'),
  ('ID-SB-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2130/3330.jpg'),
  ('ID-SB-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/2130/3330.jpg'),
  ('CN-PD-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-009', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-PD-010', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1673/3430.jpg'),
  ('CN-NS-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-31/GoogleMapsCompatible_Level12/12/1782/3340.jpg'),
  ('CN-NS-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1781/3339.jpg'),
  ('CN-NS-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1781/3339.jpg'),
  ('CN-NS-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1781/3339.jpg'),
  ('CN-NS-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1781/3339.jpg'),
  ('CN-NS-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1781/3339.jpg'),
  ('CN-NS-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1781/3340.jpg'),
  ('CN-NS-008', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1781/3339.jpg'),
  ('CN-QH-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1784/3343.jpg'),
  ('CN-QH-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1784/3343.jpg'),
  ('CN-QH-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1784/3343.jpg'),
  ('CN-QH-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1784/3343.jpg'),
  ('CN-QH-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1784/3343.jpg'),
  ('CN-QH-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1784/3343.jpg'),
  ('CN-QH-007', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_L30_Nadir_BRDF_Adjusted_Reflectance/default/2026-08-29/GoogleMapsCompatible_Level12/12/1784/3343.jpg'),
  ('CN-XM-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-08/GoogleMapsCompatible_Level9/8/110/211.jpg'),
  ('CN-XM-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-08/GoogleMapsCompatible_Level9/8/110/211.jpg'),
  ('CN-XM-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-08/GoogleMapsCompatible_Level9/8/110/211.jpg'),
  ('CN-XM-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-08/GoogleMapsCompatible_Level9/8/110/211.jpg'),
  ('CN-XM-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2026-09-08/GoogleMapsCompatible_Level9/8/110/211.jpg'),
  ('CN-NB-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1691/3430.jpg'),
  ('CN-NB-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1691/3430.jpg'),
  ('CN-NB-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1691/3430.jpg'),
  ('CN-NB-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1691/3430.jpg'),
  ('CN-NB-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-06/GoogleMapsCompatible_Level12/12/1691/3430.jpg'),
  ('HK-TK-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3348.jpg'),
  ('HK-TK-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3348.jpg'),
  ('HK-TK-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3348.jpg'),
  ('HK-TK-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3348.jpg'),
  ('HK-TK-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-TK-006', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3348.jpg'),
  ('HK-HF-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-HF-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-HF-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-HF-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-HF-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-KT-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-KT-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-KT-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-KT-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-KT-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3347.jpg'),
  ('HK-TP-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1785/3346.jpg'),
  ('HK-TP-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1785/3347.jpg'),
  ('HK-TP-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1785/3346.jpg'),
  ('HK-TP-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1785/3346.jpg'),
  ('HK-TP-005', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1786/3347.jpg'),
  ('HK-TC-001', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3344.jpg'),
  ('HK-TC-002', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3344.jpg'),
  ('HK-TC-003', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3344.jpg'),
  ('HK-TC-004', 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/HLS_S30_Nadir_BRDF_Adjusted_Reflectance/default/2026-09-05/GoogleMapsCompatible_Level12/12/1787/3344.jpg')
) AS t(id, url)
WHERE c.id = t.id;
