/**
 * npm run db:migrate
 *
 * Applies db/migrations/*.sql in filename order against DATABASE_URL, each file in one
 * transaction, recording what has been applied in `schema_migrations` so a rerun is a no-op.
 *
 *   npm run db:migrate                     apply anything not yet applied
 *   npm run db:migrate -- --reset          drop the public schema first, then apply everything
 *   npm run db:migrate -- --list           show what is applied and what is pending
 *   npm run db:migrate -- --sync-sequences advance every identity sequence past the seeded rows
 *
 * The same files run against PGlite + PostGIS locally and postgis/postgis:16-3.4 under
 * compose. The SQL is identical on both; only the DATABASE_URL host differs.
 */
import { readdir, readFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import process from 'node:process'

import { Client } from 'pg'
import 'dotenv/config'

const MIGRATIONS_DIR = resolve(process.cwd(), 'db/migrations')

export async function listMigrationFiles(dir = MIGRATIONS_DIR): Promise<string[]> {
  const entries = await readdir(dir)
  return entries.filter((f) => f.endsWith('.sql')).sort()
}

function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex')
}

async function ensureMigrationsTable(client: Client): Promise<void> {
  await client.query(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      filename    TEXT PRIMARY KEY,
      checksum    TEXT NOT NULL,
      applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `)
}

/**
 * Drops every view, table and enum in `public` that the migrations created.
 *
 * Deliberately NOT `DROP SCHEMA public CASCADE`: PostGIS installs itself into `public`, so
 * dropping the schema takes the extension with it. On PGlite that corrupts the data
 * directory outright. This drops only what the migrations own, by skipping anything an
 * extension depends on, which leaves `spatial_ref_sys` and the PostGIS functions in place.
 */
export async function resetMigrationObjects(client: Client): Promise<void> {
  await client.query(`
    DO $$
    DECLARE r record;
    BEGIN
      FOR r IN
        SELECT c.relname FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relkind = 'v'
          AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = c.oid AND d.deptype = 'e')
      LOOP
        EXECUTE format('DROP VIEW IF EXISTS public.%I CASCADE', r.relname);
      END LOOP;

      FOR r IN
        SELECT c.relname FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relkind = 'r'
          AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = c.oid AND d.deptype = 'e')
      LOOP
        EXECUTE format('DROP TABLE IF EXISTS public.%I CASCADE', r.relname);
      END LOOP;

      FOR r IN
        SELECT t.typname FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = 'public' AND t.typtype = 'e'
          AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = t.oid AND d.deptype = 'e')
      LOOP
        EXECUTE format('DROP TYPE IF EXISTS public.%I CASCADE', r.typname);
      END LOOP;
    END $$;
  `)
}

/**
 * Advances every identity sequence past the largest id already in its table.
 *
 * The id columns are `GENERATED BY DEFAULT AS IDENTITY`, so a seed file may insert explicit
 * ids. That does not move the sequence, and the next insert without an id then collides on
 * the primary key. It bites exactly where it is least welcome: `/rules` writes a NEW active
 * `rule_sets` row on every save, which is AC-9. Call this at the end of seeding.
 */
export async function syncIdentitySequences(
  client: Client,
  log: (msg: string) => void = () => {},
): Promise<number> {
  const { rows } = await client.query<{ table_name: string; column_name: string }>(`
    SELECT c.table_name, c.column_name
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_schema = c.table_schema AND t.table_name = c.table_name
    WHERE c.table_schema = 'public'
      AND t.table_type = 'BASE TABLE'
      AND c.is_identity = 'YES'
    ORDER BY c.table_name
  `)

  for (const { table_name, column_name } of rows) {
    await client.query(
      `SELECT setval(
         pg_get_serial_sequence($1, $2),
         COALESCE((SELECT max(${column_name}) FROM ${table_name}), 0) + 1,
         false
       )`,
      [table_name, column_name],
    )
    log(`[migrate] sequence synced: ${table_name}.${column_name}`)
  }

  return rows.length
}

export async function migrate(
  connectionString: string,
  options: {
    reset?: boolean
    list?: boolean
    syncSequences?: boolean
    dir?: string
    log?: (msg: string) => void
  } = {},
): Promise<{ applied: string[]; skipped: string[] }> {
  const dir = options.dir ?? MIGRATIONS_DIR
  const log = options.log ?? ((msg: string) => console.log(msg))

  const client = new Client({ connectionString })
  await client.connect()

  try {
    if (options.reset) {
      await resetMigrationObjects(client)
      log('[migrate] dropped every view, table and enum the migrations own')
    }

    if (options.syncSequences) {
      const n = await syncIdentitySequences(client, log)
      log(`[migrate] ${n} identity sequence(s) synced`)
      return { applied: [], skipped: [] }
    }

    await ensureMigrationsTable(client)

    const files = await listMigrationFiles(dir)
    const { rows } = await client.query<{ filename: string; checksum: string }>(
      'SELECT filename, checksum FROM schema_migrations',
    )
    const done = new Map(rows.map((r) => [r.filename, r.checksum]))

    if (options.list) {
      for (const file of files) {
        const state = done.has(file) ? 'applied' : 'pending'
        log(`[migrate] ${state.padEnd(7)} ${file}`)
      }
      return { applied: [], skipped: files.filter((f) => done.has(f)) }
    }

    const applied: string[] = []
    const skipped: string[] = []

    for (const file of files) {
      const sql = await readFile(join(dir, file), 'utf8')
      const checksum = sha256(sql)
      const previous = done.get(file)

      if (previous !== undefined) {
        if (previous !== checksum) {
          throw new Error(
            `${file} has changed since it was applied. Migrations are append-only; ` +
              `add a new file, or rerun with --reset on a throwaway database.`,
          )
        }
        skipped.push(file)
        continue
      }

      await client.query('BEGIN')
      try {
        await client.query(sql)
        await client.query('INSERT INTO schema_migrations (filename, checksum) VALUES ($1, $2)', [
          file,
          checksum,
        ])
        await client.query('COMMIT')
      } catch (err) {
        await client.query('ROLLBACK')
        throw new Error(`${file} failed: ${(err as Error).message}`)
      }

      applied.push(file)
      log(`[migrate] applied ${file}`)
    }

    for (const file of skipped) log(`[migrate] already applied ${file}`)

    return { applied, skipped }
  } finally {
    await client.end()
  }
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2)
  const connectionString = process.env.DATABASE_URL

  if (!connectionString) {
    console.error('[migrate] DATABASE_URL is not set. Copy .env.example to .env.')
    process.exit(1)
  }

  const result = await migrate(connectionString, {
    reset: argv.includes('--reset'),
    list: argv.includes('--list'),
    syncSequences: argv.includes('--sync-sequences'),
  })

  if (!argv.includes('--list') && !argv.includes('--sync-sequences')) {
    console.log(
      `[migrate] done: ${result.applied.length} applied, ${result.skipped.length} already present`,
    )
  }
}

const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (invokedDirectly) {
  main().catch((err) => {
    console.error('[migrate]', (err as Error).message)
    process.exit(1)
  })
}
