/**
 * scripts/gen-portfolio-sql.ts  ->  db/seed/03_portfolio.sql
 *
 * STOPGAP, owned by worker A, written because the file it produces did not exist
 * and its absence made the whole Vitest db project fail in global setup:
 * `04_samples.sql` cannot reference pins that were never loaded.
 *
 * Plan 4.1 assigns `db/seed/03_portfolio.sql` to S5, "from gen_portfolio.py". The
 * generator writes `data/synthetic/*.csv` and has no SQL emitter, so this reads
 * those CSVs and emits the seed. It follows the convention already established by
 * `scripts/gen-reference-sql.ts`, which generates 02 from TypeScript rather than
 * from Python.
 *
 * DELETE THIS FILE if `prep/gen_portfolio.py` grows its own emitter. Two
 * generators for one seed file is exactly the duplication ADR-2 exists to
 * prevent, and this one is the copy that should go.
 *
 * It derives nothing. Every column is copied from the CSV, except `geom`, which
 * is `ST_SetSRID(ST_MakePoint(lon, lat), 4326)::geography` because the schema
 * stores a point rather than two floats. It deliberately does NOT write
 * `damage_class`: the six-to-three classification is a rule and lives in the
 * seeded `building_damage_class` table (ADR-2).
 *
 * Run: npx tsx scripts/gen-portfolio-sql.ts [--source=synthetic|frozen]
 * Never edit db/seed/03_portfolio.sql by hand; edit this and regenerate.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const OUT = resolve(process.cwd(), 'db/seed/03_portfolio.sql');

/** Minimal RFC 4180 reader: the addresses carry commas inside quotes. */
function parseCsv(text: string): Record<string, string>[] {
  const rows: string[][] = [];
  let field = '';
  let row: string[] = [];
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else inQuotes = false;
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') {
      row.push(field);
      field = '';
    } else if (c === '\n') {
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else if (c !== '\r') field += c;
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }

  const header = rows.shift();
  if (!header) return [];
  return rows
    .filter((r) => r.length === header.length)
    .map((r) => Object.fromEntries(header.map((h, i) => [h, r[i]])));
}

function sqlText(value: string | undefined | null): string {
  if (value === undefined || value === null || value === '') return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumber(value: string | undefined): string {
  if (value === undefined || value.trim() === '') return 'NULL';
  return value.trim();
}

function sqlBool(value: string | undefined, fallback: boolean): string {
  if (value === undefined || value.trim() === '') return fallback ? 'true' : 'false';
  return ['true', 't', '1', 'yes'].includes(value.trim().toLowerCase()) ? 'true' : 'false';
}

/** Emits multi-row VALUES in batches, so no single statement is megabytes long. */
function batched(rows: string[], batch = 100): string[] {
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += batch) {
    out.push(rows.slice(i, i + batch).join(',\n'));
  }
  return out;
}

function main(): void {
  const arg = process.argv.slice(2).find((a) => a.startsWith('--source='));
  const source = arg ? arg.split('=')[1] : 'synthetic';
  const dir = resolve(process.cwd(), `data/${source}`);

  const read = (name: string) => parseCsv(readFileSync(resolve(dir, `${name}.csv`), 'utf8'));

  const applicants = read('applicants');
  const collateral = read('collateral');
  const loans = read('loan_applications');

  const parts: string[] = [];
  parts.push(`-- db/seed/03_portfolio.sql
--
-- GENERATED by \`npx tsx scripts/gen-portfolio-sql.ts --source=${source}\`.
-- Do not hand-edit; edit the generator and regenerate.
--
-- The synthetic portfolio: ${applicants.length} applicants, ${collateral.length} collateral pins
-- and ${loans.length} loan applications, from prep/gen_portfolio.py's CSVs.
--
-- Every applicant, loan and appraisal here is generated. The ribbon on every
-- screen says so, and \`applicants.synthetic\` is true on every row.
--
-- The six pinned fixtures of plan 4.3.2 are MEMBERS of these ${collateral.length}, occupying
-- the slot named by their per-cluster running index, so every cluster count and
-- the total are unchanged.
--
-- This writes building_type and NOT damage_class: the six-to-three
-- classification is a rule and lives in the seeded building_damage_class table
-- (ADR-2).
`);

  parts.push(`-- ${applicants.length} applicants`);
  const applicantRows = applicants.map(
    (a) =>
      `  (${sqlText(a.id)}, ${sqlText(a.name)}, ${sqlText(a.kind)}, ${sqlText(a.country)}, ${sqlBool(a.synthetic, true)})`,
  );
  for (const chunk of batched(applicantRows)) {
    parts.push('INSERT INTO applicants (id, name, kind, country, synthetic) VALUES');
    parts.push(chunk);
    parts.push(`ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, kind = EXCLUDED.kind, country = EXCLUDED.country,
  synthetic = EXCLUDED.synthetic;
`);
  }

  parts.push(`-- ${collateral.length} collateral pins. geom is a geography point, so the map and`);
  parts.push('-- v_hotspot_membership read one column rather than two floats (ADR-7).');
  const collateralRows = collateral.map(
    (c) =>
      `  (${sqlText(c.id)}, ${sqlText(c.address_line)}, ${sqlText(c.cluster_name)}, ${sqlText(c.country)},` +
      ` ST_SetSRID(ST_MakePoint(${sqlNumber(c.lon)}, ${sqlNumber(c.lat)}), 4326)::geography,` +
      ` ${sqlText(c.building_type)}, ${sqlText(c.occupancy_class)}, ${sqlNumber(c.appraised_value_sgd)},` +
      ` ${sqlNumber(c.floor_level)}, ${sqlNumber(c.elevation_m)}, ${sqlNumber(c.dist_to_coast_km)},` +
      ` ${sqlText(c.adaptation_project_id)}, ${sqlBool(c.landslide_flag, false)}, ${sqlNumber(c.slope_deg)},` +
      ` ${sqlText(c.satellite_thumb_path)})`,
  );
  for (const chunk of batched(collateralRows)) {
    parts.push(`INSERT INTO collateral (
  id, address_line, cluster_name, country, geom, building_type, occupancy_class,
  appraised_value_sgd, floor_level, elevation_m, dist_to_coast_km,
  adaptation_project_id, landslide_flag, slope_deg, satellite_thumb_path
) VALUES`);
    parts.push(chunk);
    parts.push(`ON CONFLICT (id) DO UPDATE SET
  address_line = EXCLUDED.address_line, cluster_name = EXCLUDED.cluster_name,
  country = EXCLUDED.country, geom = EXCLUDED.geom,
  building_type = EXCLUDED.building_type, occupancy_class = EXCLUDED.occupancy_class,
  appraised_value_sgd = EXCLUDED.appraised_value_sgd, floor_level = EXCLUDED.floor_level,
  elevation_m = EXCLUDED.elevation_m, dist_to_coast_km = EXCLUDED.dist_to_coast_km,
  adaptation_project_id = EXCLUDED.adaptation_project_id,
  landslide_flag = EXCLUDED.landslide_flag, slope_deg = EXCLUDED.slope_deg,
  satellite_thumb_path = EXCLUDED.satellite_thumb_path;
`);
  }

  parts.push(`-- ${loans.length} loan applications, originated 2025, which is the ADR-5 base year.`);
  const loanRows = loans.map(
    (l) =>
      `  (${sqlText(l.id)}, ${sqlText(l.applicant_id)}, ${sqlText(l.collateral_id)}, ${sqlText(l.segment)},` +
      ` ${sqlNumber(l.requested_amount ?? l.requested_amount_sgd)}, ${sqlNumber(l.originated_year) === 'NULL' ? '2025' : sqlNumber(l.originated_year)},` +
      ` ${sqlNumber(l.base_ltv_override)}, ${sqlText(l.status || 'open')}, ${sqlText(l.opened_at)}::timestamptz)`,
  );
  for (const chunk of batched(loanRows)) {
    parts.push(`INSERT INTO loan_applications (
  id, applicant_id, collateral_id, segment, requested_amount, originated_year,
  base_ltv_override, status, opened_at
) VALUES`);
    parts.push(chunk);
    parts.push(`ON CONFLICT (id) DO UPDATE SET
  applicant_id = EXCLUDED.applicant_id, collateral_id = EXCLUDED.collateral_id,
  segment = EXCLUDED.segment, requested_amount = EXCLUDED.requested_amount,
  originated_year = EXCLUDED.originated_year,
  base_ltv_override = EXCLUDED.base_ltv_override, status = EXCLUDED.status,
  opened_at = EXCLUDED.opened_at;
`);
  }

  parts.push(`-- The count AC-13 rests on. Failing here beats discovering it on stage.
DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM collateral;
  IF n <> ${collateral.length} THEN
    RAISE EXCEPTION '03_portfolio.sql expected ${collateral.length} collateral pins, found %', n;
  END IF;
END $$;
`);

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, parts.join('\n'), 'utf8');
  console.log(
    `[portfolio-sql] wrote ${OUT}: ${applicants.length} applicants, ` +
      `${collateral.length} collateral, ${loans.length} loans (source=${source})`,
  );
}

const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) main();
